// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"learn-go/modules/auth/controllers"
	"learn-go/modules/auth/services"
	controllers2 "learn-go/modules/home/controllers"
	"learn-go/modules/users/models"
	"learn-go/routes"
)

// Injectors from provider.go:

// InitializeController  initializes the Controller using Wire
func InitializeController() (*routes.Router, error) {
	user := models.NewUserModel()
	auth := services.NewAuthService(user)
	authController := controllers.NewAuthController(auth)
	homeController := controllers2.NewHomeController()
	router := routes.NewRouter(authController, homeController)
	return router, nil
}
